### ISSUE TITLE
[BUG] 导入机场订阅弹窗错误 For input string : "1.0737418565058E+15"

### ISSUE THREAD

**Issue by Eric20030401** [MetaCubeX/ClashMetaForAndroid#104]
### Feature Description

导入机场订阅弹窗错误 For input string : "1.0737418565058E+15"

**Comment by stevejohnson7** [comment]
请给出对应的订阅信息
另外，请先前往https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha尝试一下最新pre-release版，内核已升级到最新

**Comment by Geniucker** [comment]
感觉和meta内核无关，因为现在手机上下载配置文件再导入文件是可以正常使用的，但是直接再cmfa里面下载就会报这个错

**Comment by Geniucker** [comment]
看了，但是还是没明白问题在哪里，是配置文件里的字符串应该加引号，还是url链接里面要加引号（感觉不太对）
但是如果是配置文件少引号，应该直接导入文件也用不了
疑惑了

**Comment by xishang0128** [comment]
@Geniucker 是机场下发的信息
