### ISSUE TITLE
hysteria升级到 1.2.1，客户端失效

### ISSUE THREAD

**Issue by teddy780102** [MetaCubeX/ClashMetaForAndroid#11]
### 功能描述

hysteria升级到 1.2.1，手机clashmeta客户端就连不上了，怎么解决

**Comment by snakexgc** [comment]
[TCP] dial PROXY (match RuleSet(telegramcidr)) to xxx.xxx.xxx.xxx:443 error: timeout: no recent network activity

这是日志信息，希望能有所帮助

**Comment by PikachuCN** [comment]
核心基本都是这样子，把伪装改成udp好像就好，暂时不要用wechat-video

**Comment by stevejohnson7** [comment]
最新pre-release已经支持hysteria2，请前往https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha下载使用。稍后会发正式版
