### ISSUE TITLE
[BUG] core下指定的submodule对应的内核链接已经失效了

### ISSUE THREAD

**Issue by yuWorm** [MetaCubeX/ClashMetaForAndroid#110]
### 描述此错误

core下指定的submodule对应的git地址已经失效了，访问直接404，git submodule update --init --recursive也拉不下

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
无
```

### 日志

```raw
fatal: remote error: upload-pack: not our ref 0b1ed1da19e70960b80a25e1b5e03409353e0f84
fatal: Fetched in submodule path 'core/src/foss/golang/clash', but it did not contain 0b1ed1da19e70960b80a25e1b5e03409353e0f84. Direct fetching of that commit failed.
```

**Comment by stevejohnson7** [comment]
已全部update。等待新版发布
