### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by TingTing1990** [MetaCubeX/ClashMetaForAndroid#112]
初次安装使用是在git上下载的，发现在google play也有，可以直接在google play上更新吗？

谢谢！

**Comment by Skyxim** [comment]
@TingTing1990 至少据我所知没有上 play

**Comment by Skyxim** [comment]
@TingTing1990 可能是别人编译上架的，自行判断

**Comment by AnyoeDove** [comment]
https://play.google.com/store/apps/details?id=com.github.metacubex.clash.meta

问问这位 @douglarek ？

**Comment by handsomexdd1024** [comment]
建议的更新渠道是F-Droid, 虽然有时候会落后一点但也是类似应用市场的更新

**Comment by TingTing1990** [comment]
多谢，已在F-D重新下载，更新方便点。

**Comment by stevejohnson7** [comment]
duplicated #134
