### ISSUE TITLE
New version[Feature Request] 

### ISSUE THREAD

**Issue by Ght55** [MetaCubeX/ClashMetaForAndroid#117]
### Feature Description

New version

**Comment by Ght55** [comment]
Pls  add speed test config load. New version ✅️
🧭

**Comment by Ght55** [comment]
Bug

**Comment by stevejohnson7** [comment]
Pre-release has released with newest meta core. Please go to https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha to download.
