### ISSUE TITLE
测速10多次后，测速按钮一直停留在loading的状态，没有测速结果返回[BUG]

### ISSUE THREAD

**Issue by candiceatwb** [MetaCubeX/ClashMetaForAndroid#12]
### 描述此错误

有时测速会没有结果

### 如何复现该错误

步骤 1: 在节点页面，
步骤 2: 点击 测速 按钮，
步骤 3: 重复上述步骤 10多次后，测速按钮一直在loading,也没有测速结果返回

### 设备信息

- 机型: 小米/oppo
- 系统类型: MIUI
- Android 版本: 11

### 应用信息

- 版本: 2.5.9
- 安装包文件名: 
- 应用来源:  [github release](https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/v2.5.9)

### 配置文件

```yml
无
```

### 日志

```raw
可百分百重现
```

**Comment by stevejohnson7** [comment]
不要滥用测速，容易导致节点被封
