### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ldh1983** [MetaCubeX/ClashMetaForAndroid#127]
### 描述此错误

打开闪退

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
无法复现，打开马上闪退。

### 设备信息

- 机型:红米k60pro
- 系统类型:miui14
- Android 版本:13

### 应用信息

- 版本:2.8.8alpha
- 安装包文件名:cmfa-2.8.8-meta-alpha-arm64-v8a-release.apk

- 应用来源:github

### 配置文件

```yml
试了几个配置文件都闪退
```

### 日志

```raw
无发获取
```

**Comment by stevejohnson7** [comment]
请给出配置文件，可能有不兼容的节点

**Comment by ldh1983** [comment]
现在没有这个问题了。有一段时间没用这个了。原因是用几个小时就自杀。且不知meta核心把安卓的包名规则给取消了。

**Comment by stevejohnson7** [comment]
> 现在没有这个问题了。有一段时间没用这个了。原因是用几个小时就自杀。且不知meta核心把安卓的包名规则给取消了。

今天稍后应该会发一个新版，可以试试新版效果如何

**Comment by ldh1983** [comment]
现在包名规则能够可以生效，但设置了包名规则的app发出的大部分连接都没走包名规则，我设置的油管音乐，只有发出的广告连接走了包名规则，其它的按ruleset YouTube规则走。然后log记录上，有的能显示哪个app发出了连接，这种以172.19.0.1开头，有的不能，以127.0.0.0开头。见图。
![Uploading Screenshot_2023-10-24-07-53-14-444_com.github.metacubex.clash.meta.jpg…]()

**Comment by stevejohnson7** [comment]
唔，你先检查一下是不是ruleset youtube写在前面了，规则是有前后优先级顺序的
如果确定没问题的话开一个新的Issue说说情况吧，这边这个崩溃的就先关了
