### ISSUE TITLE
[BUG] 应用的Android TV版图标仍然是原版clash的样式

### ISSUE THREAD

**Issue by mdogwoop** [MetaCubeX/ClashMetaForAndroid#13]
### 描述此错误

如图
![IMG_20221014_224625](https://user-images.githubusercontent.com/64186089/195875554-d261a3aa-34a3-4ecb-821c-63ec69f6ab7a.jpg)
上为原版下为Meta

### 如何复现该错误

步骤 1: 在Android TV/Google TV设备上安装
步骤 2: 没了

### 设备信息

- 机型: Chromecast with Google TV
- 系统类型: Google TV/Android TV 
- Android 版本: 10

### 应用信息

- 版本:2.5.11
- 安装包文件名:com.github.metacubex.clash.meta_205011.apk
- 应用来源:F-Droid

### 配置文件

```yml
无关
```

### 日志

```raw
无关
```

**Comment by cubemaze** [comment]
下版本修复
