### ISSUE TITLE
[Feature Request] 希望增加meta对Hysteria2的支持，以及能提供相关插件下载

### ISSUE THREAD

**Issue by STEVENTAN100** [MetaCubeX/ClashMetaForAndroid#133]
### 功能描述

Hysteria2今天突然更新，并且与Hysteria1不兼容，希望作者能尽快更新，谢谢！

**Comment by baiyigumeng** [comment]
+1

**Comment by stevejohnson7** [comment]
最新pre-release已经支持，请前往https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha下载使用。稍后会发正式版

**Comment by cyfex** [comment]
> 最新pre-release已经支持，请前往[https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha下载使用。稍后会发正式版](https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8%E3%80%82%E7%A8%8D%E5%90%8E%E4%BC%9A%E5%8F%91%E6%AD%A3%E5%BC%8F%E7%89%88)

So far so good. Appreciate the efforts.
