### ISSUE TITLE
[Feature Request] 希望尽快更新1.16.0内核支持hysteria 2协议

### ISSUE THREAD

**Issue by helperhui** [MetaCubeX/ClashMetaForAndroid#144]
### 功能描述

希望尽快更新1.16.0内核支持hysteria 2协议

**Comment by CkBcDD** [comment]
+1

**Comment by CkBcDD** [comment]
+1
当然如果急着用的话可以先自行编译

**Comment by Jetereting** [comment]
+1

**Comment by JAXo-China** [comment]
+1

**Comment by JAXo-China** [comment]
手机用这个协议会快很多。。。

**Comment by st7105** [comment]
+1

**Comment by CberYellowstone** [comment]
+1

**Comment by baiyigumeng** [comment]
+1

**Comment by kogekiplay** [comment]
+10086

**Comment by caiysmy** [comment]
+1s

**Comment by liyk-master** [comment]
> +1 当然如果急着用的话可以先自行编译
> 
> re. 说是说可以编译，但1.16.0都出来一周了还是建议官方早日适配（

怎么自行编译，你编译了没，分享下呗

**Comment by yourber** [comment]
我说咋不行啊，原来还不支持hysteria 2啊

**Comment by Bear-biscuit** [comment]
> > +1 当然如果急着用的话可以先自行编译
> > 
> > re. 说是说可以编译，但1.16.0都出来一周了还是建议官方早日适配（
> 
> 怎么自行编译，你编译了没，分享下呗

我编译好了，有需要可以来拿[]()https://github.com/Bear-biscuit/ClashMetaForAndroid/releases

**Comment by stevejohnson7** [comment]
最新pre-release已经支持，请前往https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha下载使用。稍后会发正式版
