### ISSUE TITLE
啥时候增加hy2支持啊大佬。[Feature Request] 

### ISSUE THREAD

**Issue by XlangNan** [MetaCubeX/ClashMetaForAndroid#146]
### 功能描述

啥时候能支持hys2，电脑版的内核已经可以使用了。

**Comment by baiyigumeng** [comment]
+1

**Comment by Bear-biscuit** [comment]
+1

**Comment by Jetereting** [comment]
+1

**Comment by yourber** [comment]
+1

**Comment by SanujaNS** [comment]
+1 
Waiting for the build

**Comment by HydrangeaPurple** [comment]
> ### 功能描述
> 啥时候能支持hys2，电脑版的内核已经可以使用了。
> 
> ### 附加信息
> _No response_

已经有了, 2.8.10

**Comment by Bear-biscuit** [comment]
> ### 功能描述
> 啥时候能支持hys2，电脑版的内核已经可以使用了。
> 
> ### 附加信息
> _无响应_

已经更新，但是似乎还没有发布，可以使用我的[https://github.com/Bear-biscuit/ClashMetaForAndroid/releases/tag/2.8.10](url)

**Comment by stevejohnson7** [comment]
最新pre-release已经支持，请前往https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha下载使用。稍后会发正式版
