### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ShiJie137** [MetaCubeX/ClashMetaForAndroid#150]
### 描述此错误

每次重新连接后所有选择的节点都会变成第一个，导致分流很麻烦，每次都要手动选，除非一直开着
使用gist推送，配置参考
https://github.com/DustinWin/clash-tutorials/blob/main/%E6%95%99%E7%A8%8B%E5%90%88%E9%9B%86/%E5%88%86%E4%BA%AB%E7%AF%87/%E5%88%86%E4%BA%AB%E8%87%AA%E5%B7%B1%E4%BD%BF%E7%94%A8%20Clash.Meta%20for%20Android%20%E6%90%AD%E9%85%8D%20rule-set%20%E6%96%B9%E6%A1%88%E7%9A%84%E4%B8%80%E5%A5%97%E9%85%8D%E7%BD%AE.md

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
A11

### 应用信息

- 版本:2.8.9
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
1
```

### 日志

```raw
1
```

**Comment by hang333** [comment]
启动后等待大概四五秒再点进去节点选择页面会发现自动选取了以前选的节点啊

**Comment by ShiJie137** [comment]
> 启动后等待大概四五秒再点进去节点选择页面会发现自动选取了以前选的节点啊

懂了懂了，进去太快了，要搁几秒进去才会选择哈哈，第一时间进去发现全是第一个
