### ISSUE TITLE
[BUG] hysteria基本很好用，但youtube缩略图不显示。

### ISSUE THREAD

**Issue by alcatraz-zz** [MetaCubeX/ClashMetaForAndroid#16]
### 描述此错误

你好。试过好几个不同配置。什么都好用，除了youtube缩略图不显示。昨天两个小时调配置了无成功了。windows的客户端没有这个问题。现在我用v2rayn+hysteriacore以后让安卓的v2rayng连接电脑的socks5代理。

希望clackmetaforandroid能支持简单config.json配置。"yaml"式的太难。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...
1

### 设备信息

- 机型:
- 系统类型:
- Android 版本:
荣耀安卓8

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
。
```

### 日志

```raw
。
```

**Comment by keep1earning** [comment]
@alcatraz-zz "希望clackmetaforandroid能支持简单config.json配置。"yaml"式的太难。"

这种issue的开头应该以 "[简体中文] 功能请求" 或 "[English] Feature 
Request[English] Feature Request" 出现
而非 BUG

且从本人个人观点来说大概率会被驳回

且对于YTB的略缩图不显示,你自己也尝试,且证明了其在windows客户端是可用的,那么不应该怀疑自己客户端的配置文件的问题吗(for example, dns 问题?)

**Comment by keep1earning** [comment]
对于DNS,在我的理解内,您因参考fallback dns组的DNS设置?且确保您的DNS没有被劫持(部分ISP会抢答53端口的请求),不过对于Clash.Meta+Hysteria的服务器,我并没有尝试过,但在设想内不因出现这样的问题(因为您也描述了其他客户端下,其是可用的,我目前依然怀疑是配置文件问题)

**Comment by alcatraz-zz** [comment]
刚试Matsuri，没有问题。
