### ISSUE TITLE
hysteria1.3.0更新了，麻烦大佬更新一下

### ISSUE THREAD

**Issue by fenger7** [MetaCubeX/ClashMetaForAndroid#19]
### 功能描述

hysteria1.3.0更新了，麻烦大佬更新一下

**Comment by stevejohnson7** [comment]
请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试一下最新pre-release版，内核已升级到最新，已支持hysteria2
