### ISSUE TITLE
[Feature Request] Icon is similar to Gmail at first glance when shown in the status bar..

### ISSUE THREAD

**Issue by 2ndMessiah** [MetaCubeX/ClashMetaForAndroid#21]
### Feature Description

![image](https://user-images.githubusercontent.com/22229188/200859563-5b5c12d5-8776-4e3c-bd33-e1ba1aa3f688.png)
It might bring up some illusion that I got a new mail :))

Good work tho!!!

Appreciate it

**Comment by cubemaze** [comment]
:))。well disguised
