### ISSUE TITLE
[BUG] miui14安卓13息屏后台必杀

### ISSUE THREAD

**Issue by zzzqu** [MetaCubeX/ClashMetaForAndroid#36]
### 描述此错误

息屏再立刻亮屏后台就没了，并且只在上滑无后台时或者利用模块隐藏后台时复现(点击状态栏上的图标开启代理可以复现该错误)。
正常打开代理再切换到后台息屏，亮屏后后台正常留存。
其他应用，如V2rayNG正常。
(均已开启自启动，电池无限制)
### 如何复现该错误

如上所述

### 设备信息

- 机型:小米11pro
- 系统类型:miui14
- Android 版本:安卓13

### 应用信息

- 版本:最新
- 安装包文件名:
- 应用来源:github

### 配置文件

```yml
与配置无关
```

### 日志

```raw
与日志无关
```

**Comment by stevejohnson7** [comment]
MIUI14，无法复现。请自行排查模块原因
