### ISSUE TITLE
[BUG] http订阅转换链接流量信息缺失

### ISSUE THREAD

**Issue by sun2ot** [MetaCubeX/ClashMetaForAndroid#46]
### 描述此错误

我通过在服务端自建subconverter服务完成订阅转换，但并没有配置https加密，直接通过`ip:25500/sub?`完成订阅。

经测试，
- `Clash for Windows`可正常订阅，流量信息完整，curl返回的header中包含subscription-userinfo
- `Clash Meta For Android`可正常订阅，流量信息**缺失**，curl返回的header中**包含**subscription-userinfo
 

### 如何复现该错误

如上

### 设备信息

- 机型: 红米k50
- 系统类型: Android
- Android 版本: 13

### 应用信息

Clash Meta for Android @latest

### 配置文件

```yml
http://ip:25500/getprofile?name=profiles/xxx.ini&token=xxx
```

### 日志

```raw
[root@yzh2000 subconverter]# curl --user-agent "ClashMetaForAndroid/2.6.5.Meta-Alpha"  -I -X GET "http://ip:25500/getprofile?name=profiles/xxx.ini&token=xxx"


HTTP/1.1 200 OK
Content-Disposition: attachment; filename="iKuuu"; 
filename*=utf-8''iKuuuprofile-update-interval: 24
Subscription-UserInfo: 
upload=297026217; 
download=19257990908; 
total=339097944064; expire=1680609292
Content-Type: text/plain;
charset=utf-8
Access-Control-Allow-Origin: *
Connection: closeDate: 
Sat, 11 Feb 2023 15:36:05 GMT
Content-Length: 20340
```

**Comment by perthun** [comment]
同样的问题，不过我是，直接使用订阅链接，而出现的配置文件可以显示相关信息（剩余流量和到期时间）

而使`subscriptions`订阅，或是直接使用`proxy-providers`，所有的相关信息都丢失了。

**Comment by sun2ot** [comment]
对的。
- 直接使用机场下发的订阅链接，有流量信息；
- 使用公共的订阅转换服务，也有流量信息；
- 但是自建subconverter，就没有流量信息

所以我只能推测是不是因为我没有给订阅转换服务器配置证书，导致 `http://ip:25500/sub?` 的订阅链接与 CFM 不兼容

**Comment by xishang0128** [comment]
http的，绕过了获取信息的函数，不然就报错了

**Comment by sun2ot** [comment]
> http的，绕过了获取信息的函数，不然就报错了

原来如此，了解了，感谢！
