### ISSUE TITLE
[BUG] Build failed with an exception: keystore password was incorrect

### ISSUE THREAD

**Issue by ha-ku** [MetaCubeX/ClashMetaForAndroid#50]
### 描述此错误

* What went wrong:
Execution failed for task ':app:packageMeta-alphaRelease'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > com.android.ide.common.signing.KeytoolException: Failed to read key android from store "/home/haku/nosync/ClashMetaForAndroid/release.keystore": keystore password was incorrect
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > com.android.ide.common.signing.KeytoolException: Failed to read key android from store "/home/haku/nosync/ClashMetaForAndroid/release.keystore": keystore password was incorrect
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > com.android.ide.common.signing.KeytoolException: Failed to read key android from store "/home/haku/nosync/ClashMetaForAndroid/release.keystore": keystore password was incorrect
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > com.android.ide.common.signing.KeytoolException: Failed to read key android from store "/home/haku/nosync/ClashMetaForAndroid/release.keystore": keystore password was incorrect
   > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
      > com.android.ide.common.signing.KeytoolException: Failed to read key android from store "/home/haku/nosync/ClashMetaForAndroid/release.keystore": keystore password was incorrect

似乎是因为build.gradle.kts里104行：
```storeFile = rootProject.file("release.keystore")```
实际上没有读取keystore.path

### 如何复现该错误

根据README.md中的步骤进行build

### 设备信息

openjdk-11-jdk: 11.0.17+8-1ubuntu2~22.04 amd64

go version go1.20.1 linux/amd64

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

### 应用信息

无

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by stevejohnson7** [comment]
keystore的password存在此仓库的secrets里面，fork仓库编译请使用build-unsigned。
