### ISSUE TITLE
[Feature Request] 希望作者不要每次新发布都用Prerelease-alpha一个tag

### ISSUE THREAD

**Issue by KyoSakuyo** [MetaCubeX/ClashMetaForAndroid#54]
### 功能描述

仅仅用Prerelease-alpha一个tag的话，Github的Realease Watch的邮箱提醒就无法侦测到更新，不会给我发送更新提醒邮件。。再加上这个项目的Telegram项目也没有相应的更新频道，就很难受唉，不想花时间再手动去看有没有更新。

**Comment by Skyxim** [comment]
alpha 只作为开发分支，release 会单独 tag，不会保留历时
