### ISSUE TITLE
[BUG] 流量统计存在问题的疑问

### ISSUE THREAD

**Issue by perthun** [MetaCubeX/ClashMetaForAndroid#60]
### 描述此错误

你们好，最近我发现流量统计存在问题，日志显示直连的流量也会被记入“XX已转发”，但通过机场流量明细确认，它并没有被转发。我想确认一下，这里是否存在误导的可能？

我最初以为是配置规则的问题或者是App出现了BUG，但多次尝试后，发现日志中的数据和机场流量明细不一致。

能否请你们的技术团队协助解决这个问题？如果需要更多信息或数据，请让我知道。

谢谢！

### 如何复现该错误

根据日志中的直连记录和流量统计，就可以发现这个问题

### 设备信息

- 机型: 红米 K40
- 系统类型: LineageOS
- Android 版本: 12

### 应用信息

- 版本: 2.7.0.Meta-Alpha
- 安装包文件名: com.github.metacubex.clash.meta
- 应用来源: F-Droid

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by Skyxim** [comment]
@perthun 流量表示的是，经由 Clash 转发的，包括直连和代理

**Comment by perthun** [comment]
@Skyxim 好的，谢谢
