### ISSUE TITLE
[Feature Request] 希望能手动替换升级内核

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/ClashMetaForAndroid#64]
### 功能描述

如题，希望能增加一个配置文件夹，用于放置核心，方便替换。

**Comment by xishang0128** [comment]
@DustinWin 不会有的,内核和app高度耦合,你想换只能换特定的

**Comment by DustinWin** [comment]
> @DustinWin 不会有的,内核和app高度耦合,你想换只能换特定的

好的，那希望在软件“关于”内能够显示当前核心版本。也希望作者大大能及时更新内核。

**Comment by xishang0128** [comment]
@DustinWin 显示版本没用的,都是合并的alpha,而不是release

**Comment by DustinWin** [comment]
> @DustinWin 显示版本没用的,都是合并的alpha,而不是release

哦，懂了，感谢回复。
