### ISSUE TITLE
[BUG] MIUI14假死，状态栏快捷键无法启动（已开启无限制）

### ISSUE THREAD

**Issue by haohaohub** [MetaCubeX/ClashMetaForAndroid#68]
### 描述此错误

MIUI14无法切换后台再切回来会假死，无法点击任何按钮必须重启。状态栏快捷键间歇性无法启动APP或者启动后要等很久才能用。电源已经开启无限制模式，允许APP自启动

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:小米11Pro
- 系统类型:MIUI14
- Android 版本:13

### 应用信息

- 版本:2.7.1
- 安装包文件名:2.7.1
- 应用来源:GitHub release

### 配置文件

```yml
配置文件
```

### 日志

```raw
无
```

**Comment by DustinWin** [comment]
同遇到，必须手动杀掉进程才可以。

**Comment by Nine499** [comment]
同遇到

**Comment by ydwg** [comment]
遇到过

**Comment by YUBear** [comment]
大概率是小米手机的问题，我以前1+的氢OS也有这个问题。但我现在用的ONE UI就没这个问题

**Comment by lainbo** [comment]
同样有这样的问题

**Comment by merrkry** [comment]
一个可能的解决方法：

- [A1 Memory](https://github.com/OneB1ank/A1Memory/releases) （最新 Beta 版本）
- [冻它](https://github.com/jark006/freezeitRelease)

除了允许自启动外，全默认配置。

目前仍然存在的问题：

- 通知栏配置名称无法正确更新。（显示为 `Not Selected`。）
- 状态栏信息更新不及时，需要把状态栏关闭再打开才能看到状态切换。
- 偶尔会有点击状态栏按钮没有作用的情况。

短暂的测试过后，**没有遇到 CMFA 卡死的问题**。即使状态栏/通知栏有异常，回到 CMFA 界面中后仍然可以正常操作。

我的用例（常驻代理，装新应用时需要改代理白名单）基本不受影响了。但**我不清楚具体是因为安装了什么/卸载了什么**解决的问题，只感觉大概是和杀后台以及墓碑有关，留给诸位大佬测试了。

**Comment by stevejohnson7** [comment]
Invalid. 我这边MIUI14一切正常。自行排查模块因素
