### ISSUE TITLE
切换网络环境后断网需要重启手机[Feature Request] 

### ISSUE THREAD

**Issue by afreedomkey** [MetaCubeX/ClashMetaForAndroid#75]
### 功能描述

每次切换网络环境大概率会断网，需要重启手机才可以，比如无线到4g,或者是室内的4g到室外的4g，只要换环境就大概率掉，想问下有知道怎么回事的吗。我不确定是配置问题还是功能本来如此

**Comment by stevejohnson7** [comment]
我这里正常。请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试最新pre-release版，内核已升级到最新
