### ISSUE TITLE
[ 添加一个订阅分流规则的功能] 

### ISSUE THREAD

**Issue by wzry623090** [MetaCubeX/ClashMetaForAndroid#77]
### 功能描述

就是在软件里头添加一个可以远程订阅的分流规则的按钮，可以指定应用使用，嗯嗯，这个规则可能，DNS的那种规则吧！，因为这个功能，我主要是，想防止DNS泄露，嗯，因为我也不会写那种规则，有这个功能的话，可以订阅第三方的规则也行， ，后问一下这个ClashMetaForAndroid 如何最大限度设置防止dns泄露，因为有些设置是英文，主要是不懂，所以问问怎么设置比较好一点？

**Comment by xishang0128** [comment]
@wzry623090 设置-覆写-dns,请

**Comment by xishang0128** [comment]
@wzry623090 如果你啥也不懂,请不要在意什么dns泄露,少看不良林

**Comment by Skyxim** [comment]
meta 所有 provider 皆由规则分发
