### ISSUE TITLE
[BUG] PROCESS-NAME 无效

### ISSUE THREAD

**Issue by lbwstco** [MetaCubeX/ClashMetaForAndroid#8]
### Describe the bug

指定应用包名的规则无效
设置
- PROCESS-NAME,com.looker.droidify,🏢️ 自用代理
实际log中，从应用中发出的请求，没有被这条规则捕获，最终走到了
 - MATCH,🐟 漏网之鱼

### To Reproduce

Step 1: 打开代理、确认应用在允许列表里
Step 2: 打开应用，捕获请求
Step 3: 使用应用，应该请求没有走PROCESS-NAME规则

### Device Info

- Device: Samsung Note20 Ultra
- ROM: ONEUI 4.1
- Android Version: 12

### Application Info

- Version: 2.5.11-pre01.Meta-Alpha
- APK filename:
- Distribution Channel: F-Droid

### Configure File

```yml
...
- PROCESS-NAME,com.looker.droidify,🏢️ 自用代理
...
 - MATCH,🐟 漏网之鱼
```

### Logs

```raw
13:19:56.999    Info: [TCP] 127.0.0.1:44174 --> apt.izzysoft.de:443 match Match using 🐟 漏网之鱼[DIRECT]
13:19:57.006    Info: [TCP] 127.0.0.1:44172 --> apt.izzysoft.de:443 match Match using 🐟 漏网之鱼[DIRECT]
13:19:57.007    Info: [TCP] 127.0.0.1:44180 --> apt.izzysoft.de:443 match Match using 🐟 漏网之鱼[DIRECT]
13:19:57.020    Info: [TCP] 127.0.0.1:44184 --> apt.izzysoft.de:443 match Match using 🐟 漏网之鱼[DIRECT]
13:19:57.021    Info: [TCP] 127.0.0.1:44168 --> apt.izzysoft.de:443 match Match using 🐟 漏网之鱼[DIRECT]
13:19:57.845    Info: [TCP] 127.0.0.1:44196 --> apt.izzysoft.de:443 match Match using 🐟 漏网之鱼[DIRECT]
```

### Additional

apt.izzysoft.de为应用发起的请求

**Comment by nukemiko** [comment]
这个问题在Meta内核上就有，它的进程匹配似乎只在Windows上生效，在Linux上等于没有。（Android也是基于Linux的）
相关问题：https://github.com/MetaCubeX/Clash.Meta/issues/542

**Comment by stevejohnson7** [comment]
duplicated #100
