### ISSUE TITLE
[BUG] 软件启动后，过一段时间会自动关闭

### ISSUE THREAD

**Issue by superLei** [MetaCubeX/ClashMetaForAndroid#80]
### 描述此错误

操作步骤:
1. 打开软件启用配置后，放置后台
2. 过一会儿或比较长的时间

问题：
软件会自动关闭

### 如何复现该错误

环境:
- moto手机x30 
- Android12
- 软件版本2.8.2
操作步骤:
1. 打开软件启用配置后，放置后台
2. 过一会儿或比较长的时间

问题：
软件会自动关闭

### 设备信息

环境:
- moto手机x30 
- Android12
- 软件版本2.8.2

### 应用信息

环境:
- moto手机x30 
- Android12
- 软件版本2.8.2

### 配置文件

```yml
无
```

### 日志

```raw
无
```

**Comment by imldy** [comment]
删除APP数据后尝试

**Comment by superLei** [comment]
上面的配置信息

**Comment by ydwg** [comment]
我也遇到过

**Comment by zyf2008Neptune** [comment]
我的也是，虽然显示是正常连接的，但需要停止再启动一下

**Comment by stevejohnson7** [comment]
大概率是安卓自身杀后台或者电池优化造成的问题。请为meta app关掉电池优化，并锁进程
