### ISSUE TITLE
[Ask] How to open yacd?

### ISSUE THREAD

**Issue by rektpartyaftermath** [MetaCubeX/ClashMetaForAndroid#87]
# How to open yacd?
I think here's no mention of it on setting, or on wiki.
But on Clash for android repository, it look like they able to use external controller, which mean, maybe there's way to use yacd with it.

**Comment by Skyxim** [comment]
@rektpartyaftermath CFA has not been implemented.

**Comment by rektpartyaftermath** [comment]
So there's no way to use yacd with cmfa/cfa?
