### ISSUE TITLE
123

### ISSUE THREAD

**Issue by f2sky** [MetaCubeX/ClashMetaForAndroid#88]

**Comment by xishang0128** [comment]
可以直接使用url添加,扫码添加也不方便,且各大机场都有提供快捷导入

**Comment by f2sky** [comment]
> 可以直接使用url添加,扫码添加也不方便,且各大机场都有提供快捷导入
为什么你觉得URL比扫码方便？不妨细说一下。

一个典型的场景，手机在不能使用 Clash 翻墙的情况下，在线传递配置只能使用国产app或工具。
拿数据线接电脑传？Mac 电脑、Android 手机怎么弄？

**Comment by f2sky** [comment]
> 可以直接使用url添加,扫码添加也不方便,且各大机场都有提供快捷导入

你是怎么得出URL比扫码方便的结论的？
更新配置的时候，Clash 不可用，你通过什么传递配置信息？国产app或工具、数据线？

**Comment by xishang0128** [comment]
@f2sky 使用PC打开官网再拿出手机扫码真的会比手机直接打开官网导入方便吗?

**Comment by f2sky** [comment]
> @f2sky 使用PC打开官网再拿出手机扫码真的会比手机直接打开官网导入方便吗?

你小学毕业了吗？
没有配置信息，你怎么访问官网？上面的话你读不懂吗？

**Comment by Karmylr** [comment]
不可能把整份配置文件做成二维码

**Comment by xiaoyangdkj** [comment]
clash meta for Android 是clash for Android的分支，你应该去上方反馈问题而不是来这里

**Comment by xiaoyangdkj** [comment]
现在的机场普遍可以通过clash快捷导入（毕竟都一个模子里出来的）且鲜少有人机验证的现象发生，URL导入对于普通人来说已经够用了，再提出增加扫码功能的话就属于是没有需求就去乱创造需求了
