### ISSUE TITLE
[Feature Request] 新机场ikun订阅地址无法导入

### ISSUE THREAD

**Issue by Eric20030401** [MetaCubeX/ClashMetaForAndroid#91]
### Feature Description

https://www.ikunjichang.top/auth/login
新机场ikun订阅地址无法导入，同一个订阅clash 2.5.12可以正常使用，同时nekobox也没有问题，导入提示报错弹窗
错误
 For input string :
"1.0737418565058E+15"
确认

**Comment by stevejohnson7** [comment]
请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试一下最新pre-release版，内核已升级到最新

**Comment by visense** [comment]
> 请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试一下最新pre-release版，内核已升级到最新

导入订阅链接时提示下面这个issue的问题
https://github.com/MetaCubeX/ClashMetaForAndroid/issues/138

按照提示移除rule中的那一行，出现本条issue的错误，

最新版问题依旧，而且
For input string :
"1.0737418565058E+15"
这个问题延续好几个版本了，请大佬看看

**Comment by Skyxim** [comment]
> > 请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试一下最新pre-release版，内核已升级到最新
> 
> 导入订阅链接时提示下面这个issue的问题 #138
> 
> 按照提示移除rule中的那一行，出现本条issue的错误，
> 
> 最新版问题依旧，而且 For input string : "1.0737418565058E+15" 这个问题延续好几个版本了，请大佬看看

机场反馈，让其为 String 类型参数添加引号，防止全数字被混淆类型
