### ISSUE TITLE
[Bug]升级2.8.5后，无法加载外部proxyprovider

### ISSUE THREAD

**Issue by lifeincage** [MetaCubeX/ClashMetaForAndroid#94]
###  系统
Lineageos19.1(Android12)
### 应用安装来源
F-Droid
###  配置文件
自定义配置文件，从外部url加载节点信息,格式如下：
`
proxy-providers:
Jichang:
    type: http
    url: https://sub.jichang.com/api/v1/client/subscribe?token=abc
    path: ./Jichang.yml
    interval: 86400
    health-check:
      enable: false
      interval: 600
      url: https://www.gstatic.com/generate_204
`
###  问题发生场景
在F-Droid升级 ClashMetaForAndroid：2.8.2 —> 2.8.5
### 报错信息
parse proxy provider Jichang error:path is not subpath of home directory:/data/user/0/com.github.metacubex.clash.meta/files/imported/xxxxxxxxxx/providers/Jichang.yml

**Comment by lifeincage** [comment]
删除所有缓存和配置后，重新导入配置文件，报相同错误。
删除app后重装也不能解决。

**Comment by gaxdel** [comment]
+1，我也是。

**Comment by gaxdel** [comment]
更新2.8.6版本后已解决。

**Comment by ouyeantai** [comment]
2.8.7,又出现相同问题

**Comment by UjuiUjuMandan** [comment]
2.8.8 看起来没有这个问题了。

**Comment by stevejohnson7** [comment]
最新版已修复。请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试一下最新pre-release版，内核已升级到最新
